version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Logging in to Docker"

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t simple-python-app .

  post_build:
    commands:
      - echo "Build Successfully"

artifacts:
  files:
    - '**/*'
